company_name: YANKA Infra
company_surname: Yanka
phone: "+91 7975676745"
email: "info@sahyadriconstruction.in"
address: 2nd Main Road, Ashok Nagar, Mandya - 571401
founder: Pavan Gowda
domain: "https://nags-p.github.io/sahyadriconsanddev.web/index.html"